In [14]:
import numpy as np
# Modify the empty list, p, so that it becomes a UNIFORM probability
# distribution over n grid cells, as expressed in a list of 
# n probabilities.
def init_distribution(n):
    p = []
    # Add your code here
    p=[1/n for i in range(n)]
    # for i in range(n):
    #   p=np.hstack([p,[1/n]])
    # End your code here
    return p
init_distribution(7)



[0.14285714285714285,
 0.14285714285714285,
 0.14285714285714285,
 0.14285714285714285,
 0.14285714285714285,
 0.14285714285714285,
 0.14285714285714285]

In [6]:
#Modify the code below so that the function sense, which 
#takes p and Z as inputs, will output the normalized 
#probability distribution, q, after multiplying the entries 
# in p according to the color in the corresponding cell in world,
# followed by normalization of the probability values
world=['green', 'red', 'red', 'green', 'green']
p = [0.2, 0.2, 0.2, 0.2, 0.2]

def sense(p, Z):
    q = np.zeros((0))
    flag=0
    for i in range(len(p)):
        if(world[i]==Z):
          q=np.hstack([q,p[i]*0.75])
        else:
          q=np.hstack([q,p[i]*0.25])
    a=q.sum()
    for i in range(len(q)):
      q[i]=q[i]/a
    return q
sense(p, 'red')

array([0.11111111, 0.33333333, 0.33333333, 0.11111111, 0.11111111])

In [7]:
#Modify the code so that it updates the probability twice
#and gives the posterior distribution after both 
#measurements are incorporated. Make sure that your code 
#allows for any sequence of measurement of any length.

# DO NOT MODIFY THE SENSE FUNCTION. JUST CALL THE SENSE FUNCTION APPROPRIATELY

p=[0.2, 0.2, 0.2, 0.2, 0.2]
world=['green', 'red', 'red', 'green', 'green']
measurements = ['red', 'green']

# Add your code here
for z in measurements:
  p=sense(p,z)
# End your code here
print(p)

[0.2 0.2 0.2 0.2 0.2]


In [16]:
def move(p,U):
  return np.roll(p,U)

p=[0,0,1,0,0]
print(move(p,1))

[0 0 0 1 0]


In [23]:
def overunder(p,U):
  p=move(p,U)*0.8+move(p,U-1)*0.1+move(p,U+1)*0.1
  return p

p=[0,0,1,0,0]

for i in range(1):
  p=overunder(p,1)
print(p)

for i in range(1000):
  p=overunder(p,1)
print(p)

[0.  0.  0.1 0.8 0.1]
[0.2 0.2 0.2 0.2 0.2]


In [24]:
measurements=['red','green']
motions=[1,1]
p=init_distribution(5)
for i in range(2):
  p=sense(p,measurements[i])
  p=overunder(p,motions[i])
print(p)

[0.21157895 0.15157895 0.08105263 0.16842105 0.38736842]
