# Google Page Rank Algorithm

- Author: Swetanjal Dutta

In this notebook, we learn and code up a simplified version of Google's Page Rank Algorithm, which is a direct application of Eigenvectors and Eigenvalues we learnt in Linear Algebra.

![image](images/1.png)

Reference to the original paper: $\href{http://ilpubs.stanford.edu:8090/422/1/1999-66.pdf}{here}$

Reference to blog:
$\href{https://www.dhruvonmath.com/2019/03/20/pagerank/}{here}$

Google Page Rank Algorithm predicts a rank for each webpage on the internet. This rank depends on the number of ingoing and outgoing links to a webpage.

You can think of rank of a webpage as follows: If a web page gets rank $1$, it means that a random web searcher who clicks links randomly would spend the most amount of time in this web page. If a web page gets rank $2$, it means that a random web searcher who keeps clicking links randomly would spend the second most amount of time in this web page and so on and so forth.

Given the structure of the web, it is very obvious to model the web as a Graph Data structure. The nodes of the graph are the web pages. Edges of the graph represent links between the web pages.

Note that the graph is a directed graph. There maybe a link from webpage 'A' to webpage 'B', it may not always be the case that there exists a link from webpage 'B' to webpage 'A'.

A graph with $N$ nodes can be represented with a $N \times N$ matrix. This matrix is known as Adjacency matrix.

$A_{ij}$ represents the weight of the edge connecting the $j^{th}$ node to the $i^{th}$ node. 
We can think of this adjacency matrix as concatenation of $N$ column vectors. The $i^{th}$ column defines the edges from node $i$ to all other nodes.

**Exercise:**
Can you draw the graph corresponding to the following adjacency matrix?

\begin{equation}
A = \begin{pmatrix}
0 & 1/2 & 0 & 0\\
1/3 & 0 & 0 & 1/2\\
1/3 & 0 & 0 & 1/2\\
1/3 & 1/2 & 1 & 0\\
\end{pmatrix}
\end{equation}

**Exercise:**
Can you write down the adjacency matrix for the following graph?
![ex1](images/2.png)

Let us normalize each column of the adjacency matrix so that the entries sum upto $1$. This is because we want to output the rank as a probability value of the amount of time spent on that webpage.

We start with equiprobable ranks for all webpages. 

We update the ranks($r$) as follows:
\begin{equation}
r(i) = \underset{j}{\sum} r(j) * A(i, j)
\end{equation}
\begin{equation}
r' = A.r
\end{equation}
The above is a recursive definition.

In [0]:
import numpy as np

In [0]:
# Complete the below function to return A after normalizing
# each of it's columns
# Normalizing a column means sum of entries in each column adds to 1.
# PLEASE USE VECTORISED CODE FOR EFFICIENCY
def normalize_columns(A):
    A=np.float32(A)
    A/=A.sum(axis=0)
    return A

In [38]:
A = np.array([[0, 0, 1, 1], [1, 0, 0, 0], [1, 1, 0, 1], [1, 1, 0, 0]])
print(normalize_columns(A))

[[0.         0.         1.         0.5       ]
 [0.33333334 0.         0.         0.        ]
 [0.33333334 0.5        0.         0.5       ]
 [0.33333334 0.5        0.         0.        ]]


**Expected Output:**

[[0.         0.         1.         0.5       ]
 [0.33333333 0.         0.         0.        ]
 [0.33333333 0.5        0.         0.5       ]
 [0.33333333 0.5        0.         0.        ]]

In [0]:
epsilon = 1e-8

In [0]:
# Complete the below function to take a matrix A and a vector r.
# Return the updated rank.
# PLEASE USE VECTORISED CODE WITHOUT LOOPS
def update_rank(A, r):
    # print(A.shape)
    # print(a.shape)
    final_rank=A@r
    return final_rank

In [0]:
# Complete the below function to check if two vectors a and b are equal
# Since we are dealing with real numbers, 
# we say two elements(x and y) are equal if abs(x - y) <= epsilon

# PLEASE USE VECTORISED CODE WITHOUT LOOPS
def check_equality(a, b):
    if(abs(a-b)<=epsilon):
      return True
    else:
      return False

In [0]:
# Complete the below function to compute ranks iteratively until 
# ranks stabilise.
# We say ranks become stabilised when the after updation the ranks
# do not change.
# Use the functions defined above.
def compute_iteratively(A, initial_rank):
    cur_rank=np.expand_dims(initial_rank, axis=1)
    prev_rank=np.zeros((cur_rank.shape[0],1))
    while True:
          flag=1
          for i in range(cur_rank.shape[0]):
            if check_equality(cur_rank[i], prev_rank[i]):
              flag=1
            else:
              flag=0
          if(flag==1):
            break
          prev_rank=cur_rank
          cur_rank=update_rank(A,cur_rank)
    return cur_rank.T

In [0]:
from numpy import linalg as la
def compute_using_eig(A, initial_rank):
    eigenvals, eigenvecs = la.eig(A)
    i=0
    for a in eigenvals:
      if(a==1):
        return normalize_columns(eigenvecs[:,i])
    return "FAILURE"
    

In [132]:
A = np.array([[0, 1, 0, 0], [1, 0, 0, 1], [1, 0, 0, 1], [1, 1, 1, 0]])
A = normalize_columns(A)
r = np.array([0.25, 0.25, 0.25, 0.25])
print("Rank computed iteratively: \n", compute_iteratively(A, r))
print("Rank computed using eigen values and eigen vectors: \n", compute_using_eig(A, r))

Rank computed iteratively: 
 [[0.12000007 0.24000015 0.24000015 0.40000024]]
Rank computed using eigen values and eigen vectors: 
 [0.12       0.24000001 0.24000001 0.39999998]


**Expected Output:**

Rank computed iteratively: 
 [0.12       0.24       0.24       0.39999999]

Rank computed using eigen values and eigen vectors: 
 [0.12 0.24 0.24 0.4 ]

In [133]:
A = np.array([[0, 0, 1, 1], [1, 0, 0, 0], [1, 1, 0, 1], [1, 1, 0, 0]])
A = normalize_columns(A)
r = np.array([0.25, 0.25, 0.25, 0.25])
print("Rank computed iteratively: \n", compute_iteratively(A, r))
print("Rank computed using eigen values and eigen vectors: \n", compute_using_eig(A, r))

Rank computed iteratively: 
 [[0.39062502 0.13194445 0.28645835 0.19097223]]
Rank computed using eigen values and eigen vectors: 
 [0.38709676 0.12903225 0.29032257 0.1935484 ]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:6: ComplexWarning: Casting complex values to real discards the imaginary part
  


**Expected Output:**

Rank computed iteratively: 

[0.38709677 0.12903226 0.29032258 0.19354839]

Rank computed using eigen values and eigen vectors: 

[0.38709677 0.12903226 0.29032258 0.19354839]